# Generated by Django 5.2.7 on 2025-11-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Número de semestre (1, 2, 3, ...).', null=True),
        ),
    ]
