# Generated by Django 5.2.7 on 2025-11-06 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_course_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('floor', models.PositiveSmallIntegerField(default=1)),
                ('is_lab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ambiente/Aula',
                'verbose_name_plural': 'Ambientes/Aulas',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('present', models.BooleanField(default=False)),
                ('course_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='academics.coursegroup')),
                ('student', models.ForeignKey(limit_choices_to={'role__name': 'Alumno'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'unique_together': {('course_group', 'student', 'date')},
            },
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('purpose', models.CharField(blank=True, max_length=120)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.room')),
                ('teacher', models.ForeignKey(limit_choices_to={'role__name': 'Docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva de ambiente',
                'verbose_name_plural': 'Reservas de ambientes',
                'unique_together': {('room', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
