# Generated by Django 5.2.8 on 2025-12-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_assignment_assignmentfile_coursetopic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='graded_at',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='graded_by',
        ),
    ]
