# Generated by Django 5.2.8 on 2025-12-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_assignmentsubmission_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Archivo que sube el docente (enunciado, PDF, etc.).', null=True, upload_to='assignments/resources/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='resource_link',
            field=models.URLField(blank=True, help_text='Link externo (Codeforces, hoja de problemas, etc.).'),
        ),
    ]
